server:
  port: ${SERVER_PORT:8081}  # Usa variable de entorno o default 8081
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: redis
      port: 6379

fragment:
  storage:
    path: /app/fragments  # Ruta dentro del contenedor

logging:
  level:
    root: INFO
    com.nodo.p2pnodo: DEBUG
  file:
    name: /var/log/p2p-node.log