version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - p2p-network

  central-service:
    build:
      context: ./centralservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - p2p-network

  p2p-node-1:
    build:
      context: ./p2pnodo
    environment:
      - SERVER_PORT=8081
      - SPRING_DATA_REDIS_HOST=redis
      - CENTRAL_SERVICE_URL=http://central-service:8080
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - central-service
    networks:
      - p2p-network

  p2p-node-2:
    build:
      context: ./p2pnodo
    environment:
      - SERVER_PORT=8082
      - SPRING_DATA_REDIS_HOST=redis
      - CENTRAL_SERVICE_URL=http://central-service:8080
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - central-service
    networks:
      - p2p-network

networks:
  p2p-network:
    driver: bridge