version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - p2p-network

  centralservice:
    build:
      context: ./centralservice/centralservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - p2p-network

  p2pnodo:
    build:
      context: ./p2pnodo/p2pnodo
    environment:
      - SERVER_PORT=8081
      - SPRING_DATA_REDIS_HOST=redis
      - CENTRAL_SERVICE_URL=http://centralservice:8080
    ports:
      - "8080"
    depends_on:
      - redis
      - centralservice
    networks:
      - p2p-network



networks:
  p2p-network:
    driver: bridge